CREATE TABLE IF NOT EXISTS jobs ( 
JOB_ID integer NOT NULL UNIQUE PRIMARY KEY, 
JOB_TITLE varchar(35) NOT NULL, 
MIN_SALARY decimal(6,0)
);

INSERT INTO jobs VALUES(1001,'OFFICER',8000);

SELECT * FROM jobs;

INSERT INTO jobs VALUES(1001,'OFFICER',8000);

SELECT * FROM JOBS;